### ISSUE TITLE
Milestone 4

### ISSUE THREAD

**Issue by leonardocustodio** [leonardocustodio/polkadart#353]
- [x] #354
- [x] #356
- [x] #357
- [x] #358
- [ ] #359
- [ ] #360

**Comment by justkawal** [comment]
Can we re-open this?

I have implemented nearly half of Multi-Sig.

**Comment by leonardocustodio** [comment]
the multisig issue is still there, closed this as we dont need a issue to list issues, it just looks that we have more issues than we should

**Comment by justkawal** [comment]
> The multisig issue is still there, closed this as we dont need a issue to list issues, it just looks that we have more issues than we should. I'm also changing and organizing the labels

Sorry about that.
